### ISSUE TITLE
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by pradeepdev-1995** [whylabs/langkit#244] opened 2024-02-29 07:02 UTC
tried hallacunation tracking via this code
```
from langkit import response_hallucination
from langkit.openai import OpenAILegacy


response_hallucination.init(llm=OpenAILegacy(model="gpt-3.5-turbo-instruct"), num_samples=1)

result = response_hallucination.consistency_check(
    prompt="Who was Philip Hayworth?",
    response="Philip Hayworth was an English barrister and politician who served as Member of Parliament for Thetford from 1859 to 1868.",
)
```
But shows error
```
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
```
langkit versions tried: langkit==0.0.28 /0.0.29/0.0.30

**Comment by FelipeAdachi** [comment] 2024-03-04 17:06
Hi @pradeepdev-1995 

This will happen if you don't provide your OpenAI keys.

Make sure you are passing it with:

```python
import openai
import os

os.environ["OPENAI_API_KEY"] = "sk-xxx"
openai.api_key = os.getenv("OPENAI_API_KEY")
```

It's important to note that `response_hallucination` requires extra LLM Calls to OpenAI.

I will also create an issue to make this error more explicit.

Let me know if that solves your issue!

**Comment by FelipeAdachi** [comment] 2024-03-21 16:27
Closing this issue assuming that the missing API key was the cause.

**Closed by FelipeAdachi** 2024-03-21 16:27 UTC
